import SwiftUI

struct PersonalHealthReportView: View {
    @Environment(\.dismiss) private var dismiss
    
    // User Data (Read-Only for Report)
    @AppStorage("userName") private var userName = "Ethan Carter"
    @AppStorage("userAge") private var userAge = "28"
    @AppStorage("lifestyleActivity") private var selectedActivity = "Regularly"
    @AppStorage("lifestyleDiet") private var selectedDiet = "Balanced"
    @AppStorage("lifestyleSmoking") private var selectedSmoking = "Never"
    @AppStorage("userBloodType") private var userBloodType = "O+" 
    @AppStorage("userGender") private var userGender = "Male"
    
    var body: some View {
        ZStack {
            Color.appBackground.ignoresSafeArea()
            
            ScrollView(showsIndicators: false) {
                VStack(alignment: .leading, spacing: 24) {
                    
                    // Header Section
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Personal Health Report")
                            .font(.largeTitle)
                            .fontWeight(.bold)
                            .foregroundColor(.appText)
                        
                        Text("Generated on \(Date().formatted(date: .abbreviated, time: .omitted))")
                            .font(.subheadline)
                            .foregroundColor(.gray)
                    }
                    
                    Divider().background(Color.gray)
                    
                    // 1. Personal Details
                    SectionHeader(title: "Patient Details")
                    
                    VStack(spacing: 0) {
                        ReportRowItem(label: "Name", value: userName)
                        Divider().background(Color.gray.opacity(0.2)).padding(.leading)
                        ReportRowItem(label: "Age", value: "\(userAge) Years")
                        Divider().background(Color.gray.opacity(0.2)).padding(.leading)
                        ReportRowItem(label: "Gender", value: userGender)
                        Divider().background(Color.gray.opacity(0.2)).padding(.leading)
                        ReportRowItem(label: "Blood Group", value: userBloodType.isEmpty ? "Not Set" : userBloodType)
                    }
                    .background(Color.appSecondaryBackground)
                    .cornerRadius(12)
                    
                    // 2. Lifestyle Habits
                    SectionHeader(title: "Lifestyle Profile")
                    
                    VStack(spacing: 0) {
                        ReportRowItem(label: "Physical Activity", value: selectedActivity)
                        Divider().background(Color.gray.opacity(0.2)).padding(.leading)
                        ReportRowItem(label: "Dietary Habits", value: selectedDiet)
                        Divider().background(Color.gray.opacity(0.2)).padding(.leading)
                        ReportRowItem(label: "Smoking Status", value: selectedSmoking)
                    }
                    .background(Color.appSecondaryBackground)
                    .cornerRadius(12)
                    
                    // 3. Risk Assessment Summary
                    SectionHeader(title: "Clinical Risk Summary")
                    
                    VStack(alignment: .leading, spacing: 16) {
                        HStack {
                            Text("Overall Score")
                                .foregroundColor(.gray)
                            Spacer()
                            Text("64/100")
                                .fontWeight(.bold)
                                .foregroundColor(.orange)
                        }
                        
                        Divider().background(Color.gray.opacity(0.2))
                        
                        Text("Top Risk Identification")
                            .font(.headline)
                            .foregroundColor(.appText)
                        
                        HStack(spacing: 12) {
                            RiskTag(title: "Cardiac (Moderate)", color: .red)
                            RiskTag(title: "Metabolic (Low)", color: .green)
                        }
                    }
                    .padding()
                    .background(Color.appSecondaryBackground)
                    .cornerRadius(12)
                    
                    Spacer()
                    
                    // Footer
                    Text("This report is generated by GenCare Assist algorithms based on provided data. It is not a substitute for professional medical advice.")
                        .font(.caption2)
                        .foregroundColor(.gray)
                        .multilineTextAlignment(.center)
                        .padding(.top, 20)
                }
                .padding()
            }
        }
        .navigationTitle("Health Report")
        .navigationBarTitleDisplayMode(.inline)
        .standardBackButton()
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                Button(action: {
                    generateAndSharePDF()
                }) {
                    Image(systemName: "arrow.down.circle.fill") // Download icon
                        .symbolRenderingMode(.hierarchical)
                        .foregroundColor(.appTint) // Use tint color
                        .font(.system(size: 20))
                }
            }
        }
        .sheet(isPresented: $showShareSheet) {
            if let url = pdfURL {
                ShareSheet(activityItems: [url])
            }
        }
    }
    
    @State private var showShareSheet = false
    @State private var pdfURL: URL?
    
    private func generateAndSharePDF() {
        let data = PDFManager.ReportData(
            userName: userName,
            userAge: userAge,
            userGender: userGender,
            userBloodType: userBloodType,
            activity: selectedActivity,
            diet: selectedDiet,
            smoking: selectedSmoking,
            score: "64/100", // Hardcoded for now as in view
            risks: [
                ("Cardiac", "Moderate", .red),
                ("Metabolic", "Low", .green)
            ],
            date: Date()
        )
        
        if let url = PDFManager.shared.generateReport(data: data) {
            self.pdfURL = url
            self.showShareSheet = true
        }
    }
}

// MARK: - Subviews
struct ReportRowItem: View {
    let label: String
    let value: String
    
    var body: some View {
        HStack {
            Text(label)
                .foregroundColor(.gray)
            Spacer()
            Text(value)
                .fontWeight(.medium)
                .foregroundColor(.appText)
        }
        .padding()
    }
}

struct RiskTag: View {
    let title: String
    let color: Color
    
    var body: some View {
        Text(title)
            .font(.caption)
            .fontWeight(.bold)
            .padding(.horizontal, 12)
            .padding(.vertical, 6)
            .background(color.opacity(0.2))
            .foregroundColor(color)
            .cornerRadius(8)
            .overlay(
                RoundedRectangle(cornerRadius: 8)
                    .stroke(color.opacity(0.5), lineWidth: 1)
            )
    }
}

#Preview {
    NavigationView {
        PersonalHealthReportView()
    }
}